version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - comic-translator-prod
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: comic-translator-backend-prod
    environment:
      - NODE_ENV=production
      - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    networks:
      - comic-translator-prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.yourcomictranslator.com`)"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: comic-translator-frontend-prod
    environment:
      - VITE_API_URL=https://api.yourcomictranslator.com
    networks:
      - comic-translator-prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yourcomictranslator.com`)"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  redis:
    image: redis:7-alpine
    container_name: comic-translator-redis-prod
    volumes:
      - redis_data:/data
    networks:
      - comic-translator-prod
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  backend_uploads:
    driver: local
  backend_logs:
    driver: local
  redis_data:
    driver: local
  letsencrypt:
    driver: local

networks:
  comic-translator-prod:
    driver: bridge
